### ISSUE TITLE
Enviromental Error

### ISSUE THREAD

**Issue by HaotianWang6897** [cszy98/SAFM#1]
Hi,

The attached required Python environment contains 153 packages. While I installed them I faced version conflicts and could not reproduce your experiments.  

I believe the attached environment is your personal environment, would you have a double-check?

Thanks,
Haotian

**Comment by cszy98** [comment]
Thanks for the reminder, I have updated the requirements.txt

**Comment by HaotianWang6897** [comment]
Hi,

I faced an installation error while running 'python setup.py install'. I still cannot reproduce the experiment. Btw, the attached required packages are still not accurate. 

'''
cd models/counter
python setup.py install

'''


running bdist_egg
running egg_info
writing count_get_cuda.egg-info/PKG-INFO
writing dependency_links to count_get_cuda.egg-info/dependency_links.txt
writing top-level names to count_get_cuda.egg-info/top_level.txt
reading manifest file 'count_get_cuda.egg-info/SOURCES.txt'
writing manifest file 'count_get_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    'build_ext': BuildExtension
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 237, in build_extensions
    self._check_abi()
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 377, in _check_abi
    check_compiler_abi_compatibility(compiler)
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 167, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 143, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/usr/local/anaconda3/envs/SAFM/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.

Thanks,
Haotian

**Comment by cszy98** [comment]
I tried it again in the new environment and did not encounter such an error. According to the error message, it seems that g++ is not installed correctly?

**Comment by cszy98** [comment]
Because it has been a long time, the previous experimental environment is no longer available. According to your attempts, what are the attached required packages that need to be added? Thanks.
